- name: Provision a GeoNode into Production
  hosts: all
  remote_user: geonode
  vars:
    app_name: fip_geonode
    github_user: vanbremer
    deploy_user: ubuntu
    code_repository: "https://github.com/vanbremer/fip_geonode.git"
    branch_name: master
    virtualenv_dir: "/home/ubuntu/.venvs"
    site_url: "http://localhost:8000/"
  roles:
     - ansible_geonode
